name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  actionlint:
    name: Check workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: rhysd/actionlint@v1.6.27
