name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Containerfiles and workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: rhysd/actionlint@v1
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
      - name: Lint Containerfiles
        run: sudo bash scripts/lint.sh

  test:
    name: Run build tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
      - name: Execute test script
        run: sudo bash scripts/test.sh
